package:
  name: "uwastro300"
  version: 0.99

requirements:
  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - jupyter
    - astropy
    - pandas
    - sympy
    - jupyterlab
    - seaborn
    - pyyaml
#    - altair 
#    - vega_datasets
#    - black
#    - nb_black

about:
  summary: This is a simple meta-package for initial class python setup
