package:
  name: "uwastro300"
  version: 0.7

requirements:
  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - jupyter
    - astropy
    - pandas
    - sympy
#    - astroquery
#    - jplephem
    - jupyterlab
    - seaborn
    - altair 
    - vega_datasets
    - black

about:
  summary: This is a simple meta-package for initial class python setup
